Config:
  autoBackup:
    Enable: false
    time: 2000
  logPath: log\
  #请使用转义符号表示"."
  key:
    key:
    enable: false
  sql:
    db: test
    url: localhost
    port:
    user:
    passwd:
  web:
    port: